dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  dynamic_color: 1.6.8
  palette_generator: ^0.3.3+3

  # State management
  provider: ^6.1.1

  # Network
  web_socket_channel: ^2.4.0
  http: ^1.1.0

  # Storage
  shared_preferences: ^2.2.2

  # Utilities
  uuid: ^4.2.1

  # Audio - Local Playback
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.18